### ISSUE TITLE
Does this plugin support unimpaired-like mappings?

### ISSUE THREAD

**Issue by Groz17** [mawkler/demicolon.nvim#5]
Hi, thanks for the plugin, it's really useful.

I wonder if it's possible for the plugin to support mappings like `[q`, `[l` (recently merged into Neovim), etc... that work with the loc/quickfix list.

I tried to use the following code:

``` lua
---@see https://github.com/mawkler/demicolon.nvim/blob/main/lua/demicolon/integrations/gitsigns.lua
vim.keymap.set('n', ']l', function()
if not vim.tbl_isempty(vim.fn.getloclist(0)) then
  require('demicolon.jump').repeatably_do(function(options)
  local direction_key = (options.forward == nil or options.forward) and ']' or '['
  vim.cmd.normal({ vim.v.count1 .. direction_key .. 'l', bang = true })
  end, { forward = true })
else
  vim.notify("No loclist detected")
end
end, {desc = "Next loclist entry"})

vim.keymap.set('n', '[l', function()
if not vim.tbl_isempty(vim.fn.getloclist(0)) then
  require('demicolon.jump').repeatably_do(function(options)
  local direction_key = (options.forward == nil or options.forward) and ']' or '['
  vim.cmd.normal({ vim.v.count1 .. direction_key .. 'l', bang = true })
  end, { forward = false })
else
  vim.notify("No loclist detected")
end
end, {desc= "Previous loclist entry"})
```

But it doesn't work. Is the code wrong or are those movements not supported?

Thanks for the attention.

**Comment by mawkler** [comment]
Great idea! I've implemented this now. Your issue was `bang = true`, which shouldn't be there in this case.

Note Neovim's built-in `]q`/`[q`/`]l`/`[l` behaviour is to jump relatively to where it remembered you were last in the jump list, which is kinda weird in my opinion, but it is what it is.

**Comment by Groz17** [comment]
While we're at it, it might be a good idea to include {[,]}<c-{q,l}> to go to the previous/next file in the quickfix/loclist.

**Comment by mawkler** [comment]
@Groz17 Is that some built-in behaviour?

**Comment by Groz17** [comment]
I think so, check out `:help cnfile`

**Comment by mawkler** [comment]
@Groz17 I've now added support for this in ee6e300
